GET http://localhost:8000/ping

###

POST http://localhost:8000/api/auth/sign-up
Content-Type: application/json

{
  "email": "adam.metal@codecool.com",
  "password": "12345"
}

###
POST http://localhost:8000/api/auth/sign-in
Content-Type: application/json

{
  "email": "adam.metal@codecool.com",
  "password": "12345"
}

###
GET http://localhost:8000/api/auth/me
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDE4ZGE0NzNiMTM3MTE2NjhlMzVkZTkiLCJlbWFpbCI6ImFkYW0ubWV0YWxAY29kZWNvb2wuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkM25DUlVUNnJzT1VBZldlSzVGLlpmLkpINHFvRmVHbmNXT1FXa01wa245M1ZBUjFod2hDZGkiLCJ0cmFjayI6W10sIl9fdiI6MCwiaWF0IjoxNjc5MzUwNTA4fQ.xqOl-2Zk0GkS1QZL5YbDwP2SWEsd-_yquwGzFSQAWhQ